# Generated by Django 6.0.3 on 2026-03-25 18:37

from django.db import migrations, models


def reset_colors_to_default(apps, schema_editor):
    Label = apps.get_model('tasks', 'Label')
    Label.objects.all().update(color='7')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reset_colors_to_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('1', 'Lavender'), ('2', 'Sage'), ('3', 'Grape'), ('4', 'Flamingo'), ('5', 'Banana'), ('6', 'Tangerine'), ('7', 'Peacock'), ('8', 'Graphite'), ('9', 'Blueberry'), ('10', 'Basil'), ('11', 'Tomato')], default='7', max_length=2),
        ),
    ]
