# Generated by Django 6.0.3 on 2026-03-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
